### ISSUE TITLE
User Story: Basic churn metrics are supported.

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/interactive_churn#13]
As a command line user, I want to know the total churn, lines added, and lines deleted of a given commit, ignoring whitespace.

For example, a commit with a patch like this:
```
@@ -0,0 +1,7 @@
+def factorial_of_five
+  fact = 1
+  (1..5).each {|n| fact*=n}
+  fact
+end
+
+puts factorial_of_five
```
Has a total churn of 6, lines added of 6, lines deleted of 0

**Comment by hvaldecantos** [comment]
I am using a sample repo that I've just created. I cannot find a way to ignore blank lines like the line number 6 in the example. I've tried `--ignore-all-space`, `--ignore-space-at-eol`, `--ignore-space-change` with no luck:
```
$ git log --ignore-all-space -p --unified=0 -1 2f7604deeb -- factorial.rb
71cfd0fce2939836 -- factorial.rb
commit 2f7604deeb70efab9d66a70171cfd0fce2939836
Author: John <john@email.edu>
Date:   Fri Feb 20 11:35:56 2015 -0500

    factorial 1

diff --git a/factorial.rb b/factorial.rb
new file mode 100644
index 0000000..bb098f0
--- /dev/null
+++ b/factorial.rb
@@ -0,0 +1,7 @@
+def factorial_of_five
+  fact = 1
+  (1..5).each {|n| fact*=n}
+  fact
+end
+
+puts factorial_of_five

```
Do I have to deal with this manually? I mean, counting blank lines, for example with a regular expression like `^+[:space]*$` for added blank lines and then subtract that to the number of inserted lines returned in `@@ -0,0 +1,7 @@`.
