### ISSUE TITLE
User Story: command-line run with revision parameter

### ISSUE THREAD

**Issue by hvaldecantos** [andymeneely/interactive_churn#4]
As a command line user, I want to see the number of lines of code added plus deleted for a specific revision in a Git repository.

For example:
```
$ ichurn --revision HEAD
churn: 25 lines
$ ichurn --revision <SHA1>
churn: 20 lines
```
Default revision is HEAD, so:

`ichurn --revision HEAD` is the same as `ichurn`

This would apply from the first commit to the revision passed as parameter, for all files.

**Comment by andymeneely** [comment]
With #6, this is redundant.
