### ISSUE TITLE
User Story: command-line run with branch parameter

### ISSUE THREAD

**Issue by hvaldecantos** [andymeneely/interactive_churn#5]
As a command line user, I want to see the number of line of code added plus deleted for a specific branch `ichurn --branch branch_name` in a Git repository.

For example:
```
$ ichurn --branch dev
Churn: 280 lines
```
This would apply to the entire history, for all files in the branch. Similar to:
```
$ git log --stat master
```

**Comment by andymeneely** [comment]
With #6, this becomes redundant.
