### ISSUE TITLE
User Story: command-line run between two revisions

### ISSUE THREAD

**Issue by hvaldecantos** [andymeneely/interactive_churn#6]
As a command line user, I want to see the number of lines of code inserted and deleted between a baseline and a new revision. Similar to `$ git log --stat HEAD^..HEAD` that would show only the last commit.

For example:
```
$ ichurn --revision-to HEAD^  --revision-from HEAD
churn: 2 lines
```
This would apply for all files in the branch in the revision range given.

**Comment by andymeneely** [comment]
Handle it more like this

```
$ ichurn HEAD^..HEAD
```
Let's use Git's flexible revision spec take care of the tough stuff for us. The above example would eventually do a `git log HEAD^..HEAD`

**Comment by andymeneely** [comment]
To test this, be sure to cover the following cases:
* Branch parameter
 * Revision range
* Revision and file
*{ Just file
