### ISSUE TITLE
Travis needs to set up git first

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/interactive_churn#7]
Looks like the travis build fails because the Git user wasn't set up. Probably should put that into `spec_helper` or something.
```
/home/travis/.rvm/rubies/ruby-2.0.0-p598/bin/ruby -I/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.2.0/lib:/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rspec-support-3.2.1/lib /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.2.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

.....Initialized empty Git repository in /home/travis/build/andymeneely/churn_test_directory/.git/

.Initialized empty Git repository in /home/travis/build/andymeneely/churn_test_directory/.git/

*** Please tell me who you are.

Run

git config --global user.email "you@example.com"

git config --global user.name "Your Name"

to set your account's default identity.

Omit --global to set the identity only in this repository.
```

**Comment by hvaldecantos** [comment]
I've set an account locally for churn_test_directory git repo and I've pushed the code SHA: bf8388770fc29c17a136d19673c36dbd9d45af1b. I've restarted the build in travis and passed, but then, I don't know why, travis is still reporting one commit behind. It can be seen in the build history.

**Comment by hvaldecantos** [comment]
Weird, after the last commit of @kayladavis github badge is green and there is no code related to the tests pushed 22d6506cce89767a488827df30668e6104c178ea
